title:              Content Monkey
email:              info@contentmonkey.com.au
description:        Digital content services
author:             Content Monkey
# baseurl:            "/startbootstrap-clean-blog-jekyll"
baseurl:            ""
url:                "https://content-monkey.github.io"

collections:
  featured:
    output: false
  teamsters:
    output: false    
  services:
    output: true       
  posts:
    output: true 
    permalink: /posts/:slug/

# Social Profiles
abn_number: 49 499 729 902
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

#Acknowledgement
acknowledgement: We acknowledge the traditional owners of the land on which we work, and pay our respects to elders, past and present.

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
   
