title: Content Monkey
email: info@contentmonkey.com.au
description: Digital content services
author: Content Monkey
icon: /assets/img/favicon.ico
# baseurl: "/startbootstrap-clean-blog-jekyll"
baseurl: ""
url: "https://content-monkey.github.io"

collections:
  featured:
    output: false
  teamsters:
    output: false    
  services:
    output: true       
  posts:
    output: true 
    permalink: /posts/:slug/

# Social Profiles
abn_number: 49 499 729 902
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

#Acknowledgement
acknowledgement: We acknowledge the traditional owners of the land on which we work, and pay our respects to elders, past and present.

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# Downgraded from jekyll-paginate-v2 to jekyll-paginate
# paginate = num of posts on posts index
markdown:           kramdown
paginate:           6
paginate_path:      "/posts/page:num/"

keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
#  - jekyll-link-attributes
   
# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  exclude: ['robots.txt']
  uglifier_args:
    harmony: true

# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

# These are the defaults
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:
